/**
 * Page assembly and the shared service-listing components.
 *
 * Linking rule, enforced here rather than trusted to the author: a service is
 * NAMED in every listing (the GBP landing page has to mention all 45 services)
 * but only LINKED when its page is published. Draft pages render as plain text,
 * so no listing can ever point at a TODO page or a 404.
 */
import { SITE } from '../data/site.mjs';
import { CATEGORIES, CATEGORY_HUB, CATEGORY_LABEL, byUrl, servicesByCategory, childrenOf } from '../data/services.mjs';
import * as chrome from './chrome.mjs';
import * as schema from './schema.mjs';

const { esc } = chrome;

/** Breadcrumb trail for a page. Web design services go Home > Services > X. */
export function trailFor(page) {
  if (page.url === '/') return [{ label: 'Home', href: '/' }];
  const home = { label: 'Home', href: '/' };
  if (page.role !== 'service') return [home, { label: page.h1.split(':')[0], href: page.url, short: true }];
  const hubUrl = page.hub;
  const mid =
    hubUrl === '/'
      ? { label: 'Services', href: '/services' }
      : { label: CATEGORY_LABEL[page.gbpCategory], href: hubUrl };
  return [home, mid, { label: page.name, href: page.url }];
}

/** Trail using the short page label for hubs and the directory. */
function cleanTrail(page) {
  if (page.url === '/') return [{ label: 'Home', href: '/' }];
  if (page.role === 'service') return trailFor(page);
  const labels = { '/services': 'All services', '/seo': 'SEO & AI search', '/local-marketing': 'Local marketing', '/consulting': 'Consulting' };
  return [{ label: 'Home', href: '/' }, { label: labels[page.url] || page.h1, href: page.url }];
}

/**
 * The compact "Everything I do" block: all 45 service names grouped by the four
 * GBP categories. Used on the homepage (Sterling Sky: the GBP landing page
 * should mention every service on the profile) and on /services.
 */
export function serviceIndexBlock({ withDescriptions = false, headingLevel = 3 } = {}) {
  const H = `h${headingLevel}`;
  return CATEGORIES.map((cat) => {
    const hub = CATEGORY_HUB[cat];
    const hubPage = byUrl(hub);
    const services = servicesByCategory(cat);
    const items = services
      .map((s) => {
        const label = esc(s.name);
        const name = s.published
          ? `<a href="${s.url}">${label}</a>`
          : `<span class="svc-soon">${label}</span>`;
        const desc =
          withDescriptions && s.gbpDescription
            ? `\n            <p>${esc(s.gbpDescription)}</p>`
            : '';
        return `          <li>\n            ${name}${desc}\n          </li>`;
      })
      .join('\n');
    return `      <div class="svc-group">
        <${H} class="svc-group-title"><a href="${hub}">${esc(cat)}</a></${H}>
        <p class="svc-group-lead">${esc(hubPage ? hubPage.meta : '')}</p>
        <ul class="svc-group-list${withDescriptions ? ' svc-group-list--detail' : ''}">
${items}
        </ul>
      </div>`;
  }).join('\n');
}

/** Hub listing: every service in this hub's category with a short blurb. */
export function hubServiceList(hubUrl) {
  const kids = childrenOf(hubUrl);
  if (!kids.length) return '';
  return kids
    .map((p) => {
      const label = esc(p.name);
      const title = p.status === 'published'
        ? `<a href="${p.url}">${label}</a>`
        : `${label} <span class="svc-soon-tag">page in progress</span>`;
      return `          <li class="hub-svc">
            <h3>${title}</h3>
            <p>${esc(p.gbpDescription || p.meta)}</p>
          </li>`;
    })
    .join('\n');
}

/** Assemble a complete HTML document. */
export function page({ page: p, body, schemaBlocks, robots }) {
  const trail = cleanTrail(p);
  const blocks = schemaBlocks || defaultSchema(p, trail);
  const isDraft = p.status === 'draft';
  const robotsValue = robots || (isDraft ? 'noindex, follow' : 'index, follow');
  return `<!DOCTYPE html>
<!-- Generated by scripts/build-pages.mjs from src/. Do not edit by hand: run \`npm run build\`. -->
<html lang="en">
<head>
${chrome.head({ page: p, schema: schema.render(blocks), robots: robotsValue })}
</head>
<body>

${chrome.nav(p.url)}

${p.role === 'service' ? chrome.breadcrumbTrail(trail) + '\n\n' : ''}  <main>
${body}
  </main>

${chrome.footer()}

${chrome.tracker()}
</body>
</html>
`;
}

function defaultSchema(p, trail) {
  const blocks = [];
  if (p.url === '/') {
    blocks.push(schema.businessEntity(), schema.founderEntity());
  } else {
    blocks.push(schema.businessReference());
  }
  if (p.covers && p.covers.length) blocks.push(...schema.serviceBlocks(p));
  blocks.push(schema.breadcrumbs(p, trail));
  return blocks;
}

export { chrome, schema, SITE };
