/**
 * Generates robots.txt and llms.txt.
 *
 * robots.txt allows everything, which was already true. What changes is that
 * the crawlers that matter are named explicitly. A wildcard already permits
 * them, so this is documentation of intent rather than a behaviour change: it
 * makes it obvious to anyone reading the file (including Owen in six months)
 * that AI crawlers are deliberately allowed rather than overlooked.
 *
 * Nothing is disallowed at all, deliberately. /card and /blog carry noindex
 * meta tags, and a page blocked in robots.txt cannot be fetched, so a crawler
 * never sees the noindex and the page can still end up indexed from an
 * external link. Noindex only works on a page that is allowed to be crawled.
 *
 * llms.txt is a proposed convention, not a standard, and Google has stated no
 * special file is required for AI Overviews. It is generated here because it
 * costs nothing: the data already exists, so it cannot drift.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE } from '../src/data/site.mjs';
import { CATEGORIES, CATEGORY_HUB, CATEGORY_LABEL, servicesByCategory, byUrl, published } from '../src/data/services.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Search engines, then the AI crawlers and answer engines, named explicitly. */
const AGENTS = [
  'Googlebot', 'Googlebot-Image', 'Bingbot', 'DuckDuckBot', 'Applebot',
  'GPTBot', 'OAI-SearchBot', 'ChatGPT-User',
  'ClaudeBot', 'Claude-SearchBot', 'Claude-User',
  'PerplexityBot', 'Perplexity-User',
  'Google-Extended', 'Applebot-Extended', 'meta-externalagent', 'Amazonbot', 'Bytespider', 'CCBot',
];

const robots = `# 940Digital
# Everything is open to everyone. The agents below are listed explicitly so it
# is clear that search crawlers and AI answer engines are deliberately allowed.
# Generated by scripts/build-robots.mjs. Do not edit by hand.

User-agent: *
Allow: /

${AGENTS.map((a) => `User-agent: ${a}\nAllow: /`).join('\n\n')}

Sitemap: ${SITE.origin}/sitemap.xml
`;
writeFileSync(join(ROOT, 'robots.txt'), robots);

/* llms.txt: a plain-text map of the site for language models. */
const lines = [];
lines.push(`# ${SITE.name}`);
lines.push('');
lines.push(`> ${SITE.description}`);
lines.push('');
lines.push(`940Digital is a one-person web design and search agency in Denton, Texas, serving small businesses across Denton County and the Dallas-Fort Worth metroplex. Owner and sole operator: ${SITE.founder.name}. Phone: ${SITE.phoneDisplay}. Every project starts with a working demo the client can use before paying anything.`);
lines.push('');
lines.push('## Start here');
lines.push('');
lines.push(`- [Home](${SITE.origin}/): what 940Digital does and who it is for`);
lines.push(`- [Pricing](${SITE.origin}/pricing): every plan and what it costs, in full`);
lines.push(`- [Portfolio](${SITE.origin}/work): live client sites`);
lines.push(`- [About](${SITE.origin}/about): the founder and how the business works`);
lines.push(`- [Contact](${SITE.origin}/contact): book a free consult`);
lines.push(`- [All services](${SITE.origin}/services): the full directory`);

for (const cat of CATEGORIES) {
  const hub = CATEGORY_HUB[cat];
  const hubPage = byUrl(hub);
  lines.push('');
  lines.push(`## ${cat}`);
  lines.push('');
  if (hubPage) lines.push(`${hubPage.meta}`);
  lines.push('');
  lines.push(`- [${CATEGORY_LABEL[cat]} overview](${SITE.origin}${hub})`);
  for (const s of servicesByCategory(cat)) {
    if (s.url === hub) continue;
    const p = byUrl(s.url);
    if (!p || p.status !== 'published') continue;
    lines.push(`- [${s.name}](${SITE.origin}${s.url}): ${p.meta}`);
  }
}

lines.push('');
lines.push('## Notes');
lines.push('');
lines.push('- All content is server-rendered HTML. No JavaScript is required to read any page.');
lines.push('- Service names on this site match the Google Business Profile exactly.');
lines.push('- Prices shown on the pricing page are complete. There are no undisclosed fees.');
lines.push('');

writeFileSync(join(ROOT, 'llms.txt'), lines.join('\n'));

console.log(`robots.txt: ${AGENTS.length} agents named explicitly`);
console.log(`llms.txt: ${published().length} pages mapped, ${lines.length} lines`);
