/**
 * Generates sitemap.xml from published pages only.
 *
 * Excludes drafts, anything noindex, and /card. Replaces the hand-maintained
 * file whose lastmod dates had to be refreshed by hand (see commit 8a6e401).
 *
 * lastmod comes from each output file's git commit date, so it reflects when
 * the page actually changed rather than when the build ran. Falls back to the
 * file mtime for files not yet committed.
 */
import { writeFileSync, existsSync, statSync, readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE } from '../src/data/site.mjs';
import { PAGES } from '../src/data/services.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Pages outside the service map that belong in the sitemap. */
const EXTRA = [
  { url: '/about', file: 'about.html', priority: '0.6' },
  { url: '/pricing', file: 'pricing.html', priority: '0.8' },
  { url: '/work', file: 'work.html', priority: '0.7' },
  { url: '/contact', file: 'contact.html', priority: '0.9' },
];

const PRIORITY = { homepage: '1.0', hub: '0.9', directory: '0.8', service: '0.7' };

function lastmod(file) {
  const path = join(ROOT, file);
  if (!existsSync(path)) return null;
  try {
    /* Uncommitted changes mean the page changed today, whatever git last
       recorded. Without this the lastmod would report the previous commit and
       understate a change we just made. */
    execSync(`git diff --quiet HEAD -- ${JSON.stringify(file)}`, {
      cwd: ROOT, stdio: 'ignore',
    });
    const out = execSync(`git log -1 --format=%cs -- ${JSON.stringify(file)}`, {
      cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'],
    }).toString().trim();
    if (out) return out;
  } catch { /* dirty file, not a git repo, or never committed: fall through */ }
  return statSync(path).mtime.toISOString().slice(0, 10);
}

const entries = [];

for (const p of PAGES) {
  if (p.status !== 'published') continue;
  const file = p.url === '/' ? 'index.html' : `${p.slug}.html`;
  if (!existsSync(join(ROOT, file))) continue;
  const html = readFileSync(join(ROOT, file), 'utf8');
  if (/name="robots" content="noindex/.test(html)) continue;
  entries.push({
    loc: p.url === '/' ? `${SITE.origin}/` : `${SITE.origin}${p.url}`,
    lastmod: lastmod(file),
    priority: PRIORITY[p.role] || '0.7',
  });
}

for (const e of EXTRA) {
  if (!existsSync(join(ROOT, e.file))) continue;
  const html = readFileSync(join(ROOT, e.file), 'utf8');
  if (/name="robots" content="noindex/.test(html)) continue;
  entries.push({ loc: `${SITE.origin}${e.url}`, lastmod: lastmod(e.file), priority: e.priority });
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (e) =>
      `  <url><loc>${e.loc}</loc>${e.lastmod ? `<lastmod>${e.lastmod}</lastmod>` : ''}<changefreq>monthly</changefreq><priority>${e.priority}</priority></url>`
  )
  .join('\n')}
</urlset>
`;

writeFileSync(join(ROOT, 'sitemap.xml'), xml);
console.log(`sitemap.xml: ${entries.length} URLs`);
for (const e of entries) console.log(`  ${e.priority}  ${e.lastmod}  ${e.loc}`);
